export const PLATFORM_BRAND_COLORS: { name: string; hex: string }[] = [
  { name: "Parcela Orange", hex: "#fd7e14" },
  { name: "Crimson Red", hex: "#dc2626" },
  { name: "Rose", hex: "#f43f5e" },
  { name: "Fuchsia", hex: "#d946ef" },
  { name: "Violet", hex: "#7c3aed" },
  { name: "Indigo", hex: "#4f46e5" },
  { name: "Royal Blue", hex: "#2563eb" },
  { name: "Sky Blue", hex: "#0ea5e9" },
  { name: "Cyan", hex: "#06b6d4" },
  { name: "Teal", hex: "#0d9488" },
  { name: "Emerald", hex: "#10b981" },
  { name: "Green", hex: "#22c55e" },
  { name: "Lime", hex: "#84cc16" },
  { name: "Yellow", hex: "#eab308" },
  { name: "Amber", hex: "#f59e0b" },
  { name: "Deep Orange", hex: "#ea580c" },
  { name: "Brown", hex: "#78350f" },
  { name: "Warm Slate", hex: "#64748b" },
  { name: "Stone Gray", hex: "#78716c" },
  { name: "Charcoal", hex: "#374151" },
  { name: "Navy", hex: "#1e3a5f" },
  { name: "Midnight", hex: "#1e1b4b" },
  { name: "Forest Green", hex: "#166534" },
  { name: "Olive", hex: "#4d7c0f" },
  { name: "Gold", hex: "#ca8a04" },
  { name: "Copper", hex: "#b45309" },
  { name: "Burgundy", hex: "#9f1239" },
  { name: "Maroon", hex: "#7f1d1d" },
  { name: "Plum", hex: "#6b21a8" },
  { name: "Cobalt", hex: "#1d4ed8" },
  { name: "Mint", hex: "#059669" },
  { name: "Turquoise", hex: "#0891b2" },
  { name: "Coral", hex: "#fb7185" },
  { name: "Salmon", hex: "#f97316" },
  { name: "Peach", hex: "#fed7aa" },
  { name: "Lavender", hex: "#a78bfa" },
  { name: "Dusty Rose", hex: "#e879f9" },
  { name: "Steel Blue", hex: "#3b82f6" },
  { name: "Graphite", hex: "#1c1917" },
  { name: "Silver", hex: "#9ca3af" },
];
