import type {
  ReportColumn,
  ReportRow,
  StaffReportMeta,
  StaffReportResult,
  StaffReportSummaryMetric,
} from "@/lib/staff-reports";
import { logoImageFormat } from "@/lib/brand-color-theme";

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function buildFilename(meta: StaffReportMeta, extension: string) {
  const period = meta.periodLabel.replace(/\s+/g, "");
  return `${slugify(meta.stationCode)}_${slugify(meta.reportTitle)}_${period}.${extension}`;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

function rowsToSheetData(columns: ReportColumn[], rows: ReportRow[]) {
  const headers = columns.map((column) => column.label);
  const body = rows.map((row) =>
    columns.map((column) => {
      const value = row[column.key];
      return typeof value === "number" ? value : String(value ?? "");
    })
  );
  return [headers, ...body];
}

async function loadLogoDataUrl(src: string) {
  if (src.startsWith("data:")) return src;
  const response = await fetch(src);
  const blob = await response.blob();
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

function summaryLines(summary: StaffReportSummaryMetric[]) {
  return summary.map((item) => [item.label, String(item.value)]);
}

export async function exportStaffReportExcel(
  result: StaffReportResult,
  meta: StaffReportMeta
) {
  const XLSX = await import("xlsx");

  const summarySheet = XLSX.utils.aoa_to_sheet([
    [meta.companyName, meta.companyTagline],
    ["Station", meta.stationName],
    ["Station code", meta.stationCode],
    ["Operator", meta.operator],
    ["Report", meta.reportTitle],
    ["Period", meta.periodLabel],
    ["Generated by", meta.generatedBy],
    ["Generated at", meta.generatedAt],
    [],
    ["Summary"],
    ...summaryLines(result.summary),
    [],
    ["Total records", result.rows.length],
  ]);

  const dataSheet = XLSX.utils.aoa_to_sheet(rowsToSheetData(result.columns, result.rows));

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");
  XLSX.utils.book_append_sheet(workbook, dataSheet, "Records");

  const buffer = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  downloadBlob(blob, buildFilename(meta, "xlsx"));
}

export async function exportStaffReportPdf(result: StaffReportResult, meta: StaffReportMeta) {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  if (meta.logoSrc) {
    try {
      const logo = await loadLogoDataUrl(meta.logoSrc);
      doc.addImage(logo, logoImageFormat(meta.logoSrc), 40, 28, 48, 36);
    } catch {
      // Logo optional — report still exports without it.
    }
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(meta.accentRgb[0], meta.accentRgb[1], meta.accentRgb[2]);
  doc.text(meta.companyName, 98, 44);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(meta.companyTagline, 98, 58);

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(meta.reportTitle, 40, 88);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Station: ${meta.stationName} (${meta.stationCode})`, 40, 104);
  doc.text(`Period: ${meta.periodLabel}`, 40, 118);
  doc.text(`Generated by: ${meta.generatedBy} · ${meta.generatedAt}`, 40, 132);

  if (result.summary.length > 0) {
    const summaryText = result.summary
      .map((item) => `${item.label}: ${item.value}`)
      .join("   |   ");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(summaryText, 40, 146, { maxWidth: pageWidth - 80 });
  }

  if (result.rows.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 116, 139);
    doc.text("No records matched the selected filters.", 40, 170);
  } else {
    autoTable(doc, {
      startY: 158,
      head: [result.columns.map((column) => column.label)],
      body: result.rows.map((row) =>
        result.columns.map((column) => {
          const value = row[column.key];
          return typeof value === "number" ? String(value) : String(value ?? "");
        })
      ),
      styles: { fontSize: 7, cellPadding: 4 },
      headStyles: {
        fillColor: meta.accentRgb,
        textColor: 255,
      },
      margin: { left: 40, right: 40 },
      tableWidth: pageWidth - 80,
    });
  }

  doc.save(buildFilename(meta, "pdf"));
}

export function printStaffReport() {
  window.print();
}
