import type { CSSProperties } from "react";
import type { StaffReportMeta, StaffReportResult } from "@/lib/staff-reports";

type StaffReportPrintSheetProps = {
  meta: StaffReportMeta;
  result: StaffReportResult;
};

export function StaffReportPrintSheet({ meta, result }: StaffReportPrintSheetProps) {
  return (
    <div
      id="staff-report-print"
      className="staff-report-print hidden print:block"
      style={{ "--report-accent": meta.accentColor } as CSSProperties}
      data-operator={meta.operator}
    >
      <header className="staff-report-print-header">
        <div className="flex items-center gap-4">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={meta.logoSrc}
            alt={meta.companyName}
            className="h-14 w-auto max-w-[8rem] object-contain"
          />
          <div>
            <p className="staff-report-print-company">{meta.companyName}</p>
            <p className="text-sm text-slate-600">{meta.companyTagline}</p>
          </div>
        </div>
        <div className="text-right text-sm text-slate-700">
          <p className="font-bold text-slate-900">{meta.stationName}</p>
          <p>{meta.stationCode}</p>
        </div>
      </header>

      <section className="staff-report-print-title">
        <h1>{meta.reportTitle}</h1>
        <p>
          Period: {meta.periodLabel} · Generated by {meta.generatedBy} · {meta.generatedAt}
        </p>
      </section>

      {result.rows.length === 0 ? (
        <p className="staff-report-print-empty">No records matched the selected filters.</p>
      ) : (
        <table className="staff-report-print-table">
          <thead>
            <tr>
              {result.columns.map((column) => (
                <th key={column.key}>{column.label}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {result.rows.map((row, index) => (
              <tr key={`${String(row.reference ?? row.category ?? index)}-${index}`}>
                {result.columns.map((column) => (
                  <td key={column.key}>{row[column.key] ?? "—"}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <footer className="staff-report-print-footer">
        <p>{meta.companyName} terminal report · Confidential station record</p>
        <p>Printed from the {meta.operator} staff portal</p>
      </footer>
    </div>
  );
}
